site_name: DFCogs Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
  icon:
    logo: material/cube-outline
    repo: material/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.action.edit

extra:
  social:
    - icon: material/web
      link: https://dfcogs.bedcrab.dev/
    - icon: material/github
      link: https://github.com/BedCrabDev/DFCogs-Docs
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JhFTYnBEXp

repo_url: https://github.com/BedCrabDev/DFCogs-Docs
repo_name: BedCrabDev/DFCogs-Docs
edit_uri: edit/main/docs/

plugins:
  - search